services:
  db:
    container_name: mysql
    image: mysql:8.1
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - msqldata:/var/lib/mysql
    env_file: docker.env

volumes:
  msqldata:
